### ISSUE TITLE
Als medewerker wil ik kunnen inloggen op de ZAC...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#10]
...zodat de gegevens beschermd zijn voor niet-geauthoriseerden.

Diverse medewerkers hebben verschillende rechten. Zo moet een KCC-medewerker in principe alle
(lopende) zaken kunnen inkijken, terwijl huwelijksplanner-medewerkers waarschijnlijk beperkt zijn op die relevante zaaktypen. Aan de lokale login kunnen rechten/rollen/groepen toegekend worden die zich vertalen naar API permissies.

Een meer geintegreerde versie hiervan staat beschreven in #9 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] Gebruikersaccounts kunnen aangemaakt worden
- [ ] Gebruikers kunnen aan rollen toegewezen worden
- [ ] Rollen kunnen geconfigureerd worden met scopes/zaaktypen
- [ ] Als gebruiker kan ik inloggen met gebruikersnaam + wachtwoord

**Taken**
- [ ] TODO
