### ISSUE TITLE
Als applicatiebeheerder wil ik de ZAC kunnen configureren...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#11]
...zodat ik makkelijk met een bepaalde (set aan) ZRC/DRC/ZTC kan verbinden.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] Ik kan definieren welke services gebruikt worden in welke hoedanigheid
- [ ] Ik kan meerdere services van hetzelfde type configureren
- [ ] Ik kan per service `client_id` en `secret` specifieren

**Taken**
- [ ] TODO
