### ISSUE TITLE
Als medewerker wil ik documenten kunnen toevoegen aan een zaak...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#12]
...zodat ik mensen aan de balie kan helpen.

Stap 4 van het huidige trouwproces vereist het toevoegen van documenten aan de zaak indien een persoonlijk consult nodig is. De KCC medewerker moet dan documenten kunnen toevoegen en aangeven wat voor type document het betreft.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] Ik kan naar een detailpagina van een zaak gaan
- [ ] Ik kan zien welke documenten/gegevens de zaak op dit moment heeft
- [ ] Ik kan documenten toevoegen, waarbij ik kan aangeven om welk informatieobjecttype uit het ZTC het gaat (identiteitskaart, paspoort, verblijfsvergunning...)
- [ ] Ik kan zien welke documenten aan een zaak gekoppeld zijn

**Taken**
- [ ] TODO
