### ISSUE TITLE
Als burger wil ik mijn huwelijkszaak/zaken kunnen inkijken...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#15]
...zodat ik niet langs de balie hoef langs te gaan of te telefoneren.

Vooral leuk voor demo-doeleinden - een detailpagina kan weergegeven worden mits je de zaak-identificatie kent. Dit laat in principe toe om anonieme gebruikers enkel-lezen op een zaak toe te passen.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] Als burger kan ik een zaak-identificatie invoeren om de details op te vragen
- [ ] Als burger kan ik geen gegevens wijzigen
- [ ] Eventueel moet ik als burger een wachtwoord invoeren om de pagina te kunnen bekijken

**Taken**
- [ ] TODO
