### ISSUE TITLE
AFGEVOERD: Als ontwikkelaar wil ik kunnen koppelen met de Camunda proces engine

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#221]
...zodat deze process engine alles orchestreert.

Een aantal dingen moeten onderzocht/geprototyped worden:

- [ ] API koppeling met Camunda vanuit de BInG
- [ ] reageren op events vanuit Camunda (vb. aanmaken zaak -> zaak URL registereren bij de aanvraag in BInG)
- [ ] UI laten aansturen door process-state in Camunda (wel/niet vergadering afh. van toetsingswijze)
