### ISSUE TITLE
Als medewerker wil ik dat het BInG proces in Camunda gestart wordt na het aanmelden...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#240]
...zodat de zaak afgehandeld kan worden.

Taken:

- [x] Bepalen welke variabelen gedefinieerd zijn nodig voor de start van het Camunda proces
- [x] Configureren API toegang Camunda in de admin interface
- [x] Aanroepen juiste proces in Camunda met de startvariabelen om het proces te starten (API call)
- [x] Documenteer naar Ritense welke API calls nodig zijn
