### ISSUE TITLE
The Camunda deployment in the K8S cluster is not persistent

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#263]
# Bug

When the pods/containers exit and restart, all state is wiped and uploaded definitions are gone.

The database/file storage should be made persistent.

Otherwise it's impossibel to test/develop features over the span of days/weeks. This is also a good preparation for https://github.com/GemeenteUtrecht/process-platform

- [x] Set up persistent MySQL deployment in `camunda` namespace
- [x] Make Camunda use this database
- [x] Investigate if any other PVs are needed

**Comment by sergei-maertens** [comment]
Helm templates on Gitlab are updated, and everything is re-deployed.
