### ISSUE TITLE
As a process application developer, I want to be able to test with a real application

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#264]
... so I can use actual dynamic data and real use cases.

- [x] Set up a docker-compose for the BInG app
- [x] Provide initial out-of-the-box configuration
- [x] Document credentials/login etc.
