### ISSUE TITLE
Als burger wil ik op een later moment extra stukken digitaal aan kunnen leveren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#31]
...zodat ik sommige zaken pas later hoef te regelen. 

bijvoorbeeld: https://xd.adobe.com/view/57182dfd-e5c0-4292-4340-0f931ae6be4a-2129/

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO
