### ISSUE TITLE
Check DRC implementatie

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#330]
- [x] Check filter parameters (#329)
- [x] Check autorisatie: maak EIO met IOT waartoe geen toegang ingesteld is (ok)
- [x] Check audittrail aangemaakt (ok)
