### ISSUE TITLE
Als medewerker wil met SSO/ADFS kunnen inloggen op de (beheer)applicaties 

### ISSUE THREAD

**Issue by CMasselink** [GemeenteUtrecht/ZGW#339]
zodat ik hier geen aparte username en password voor hoef te onthouden.
In generieke zin: SSO moet op elke plek toegepast worden waar medewerkers in een applicatie moeten inloggen.
Oplossingsmethodiek: ADFS. Inhoudelijke/technische details verder buiten Github om bespreken

- [x] Open Zaak admin omgeving (PR: https://github.com/open-zaak/open-zaak/pull/379)
- [x] Open Notificaties admin omgeving (PR: pending)
- [x] Camunda-Worker (PR: https://github.com/GemeenteUtrecht/camunda-worker/pull/15)
- [x] Beheerconsole
- [x] BInG
- ~~[ ] Alfresco~~

**Comment by sergei-maertens** [comment]
ADFS based SSO enabled in all Django environments
