### ISSUE TITLE
EPIC: Als functioneel beheerder wil ik een heel nieuw proces zelf kunnen inrichten

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#414]
...zodat ik hiervoor niet afhankelijk ben van een developer.

Wat ik wil kunnen:

- [x] Formulier maken en koppelen aan juiste BPMN proces
- [x] Uitvoerbaar BPMN proces maken (inclusief de juiste BPTL taken) en deployen
- [x] Een ZAC configureren
- [x] Gebruikers-autorisaties inrichten voor het proces (op rolniveau) 
- [x] Beheer-autorisaties inrichten
- [x] Applicatie-autorisaties inrichten voor het proces
- [x] Een zaaktype inrichten
- [ ] Een vernietigingsproces kunnen configureren
- [ ] Gebruikers recordmanagement autoriseren
- [ ] Queries opstellen tbv vernietigingsproces 
- [ ] Fout monitoring
- [ ] NLX configureren

**Comment by MichelleDautzenberg** [comment]
Aanvullingen hierbij @FrankHarbers @JurjenBert ?

**Comment by Tim-Hartog** [comment]
Kennis inmiddels ruimschoots aanwezig.
Wordt wel continu doorontwikkeld...
maar vergt geen aparte actie meer.
