### ISSUE TITLE
Als medewerker wil ik zaken kunnen zien in een web-interface...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#7]
...zodat ik deze zaken kan oopvolgen en beheren.

De interface heeft links filters, in het midden de lijst van zaken en rechts ruimte voor details/status-progressie.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] Ik kan selecteren welke zaaktypes ik wil weergeven (1-meerdere)
- [ ] Ik kan door pagina's van zaken heen navigeren
- [ ] Ik kan de identificatie + omschrijving van zaken zien in de titel, + eventueel startdatum...
- [ ] Ik kan een zaak in de lijst aanklikken zodat meer details in de rechterkolom zichtbaar worden
- [ ] De pagina is in de stijl van Gemeente Utrecht (afstemmen op webformulier pagina?)
- [ ] De pagina heeft een acceptabele performance (in de context van een prototype)
- [ ] Ik kan zoeken/filteren op een zaakidentificatie

**Taken**
- [ ] TODO

**Comment by JostCrow** [comment]
missende mockups.

**Comment by sergei-maertens** [comment]
Voortgang in detailweergave van een zaak... volgende stap is weergeven van documenten

![zac-zaak-detail](https://user-images.githubusercontent.com/5518550/57309513-8655bc00-70e8-11e9-83da-6978be933a13.png)
