### ISSUE TITLE
Als BInG aanvrager wil ik een notificatie ontvangen als er informatie of vragen over mijn zaak zijn.

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#84]
...zodat de behandelaar kan communiceren naar de aanvrager.

De aanvrager kan vragen hebben, of bijvoorbeeld een statusupdate wordt doorgezet.

De notificatie verloopt via e-mail.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO
