### ISSUE TITLE
Als medewerker wil ik zelf metadatatypering kunnen invoeren op WeTransfer-uploadet documenten

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#98]
...zodat de metagegevens beschikbaar zijn en het aanleveren performant blijft.

Opties:

* progress bar zodat medewerker zelf link kan invoeren + erna metadata invoeren
* afleiden met informatieobjecttypes

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO
